// vue-groceries/src/components/Title.vue
<template>
  <div class="title">
    <span class="text">{{ text }}</span>
    <a
      class="github"
      aria-label="GitHub"
      href="https://github.com/dstanich/angular-elements-presentation"
      target="_blank"
    >
      <img src="@/assets/GitHub-Mark-Light-32px.png">
    </a>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class Title extends Vue {
  @Prop() private text!: string;
}
</script>

<style scoped lang="scss">
.title {
  display: flex;
  align-content: space-between;
  align-items: center;
  background: #07531b;
  padding: 5px 15px;
  box-shadow: 0 2px 5px 0px #000000;
  color: #b0dfbc;
  margin-bottom: 5px;
}

.text {
  display: flex;
  flex: 1 1 auto;
  color: #b0dfbc;
  font-size: 1.25rem;
}

.github {
  display: flex;
  flex: 0 0 auto;
}
</style>

// react-groceries/src/title/Title.tsx
import React, { Component } from 'react';
import './Title.css';
import github from './GitHub-Mark-Light-32px.png';

interface Props {
  text: string;
}

class Title extends Component<Props, {}> {
  constructor(props: any) {
    super(props);
  }

  render() {
    return (
      <div className="Title">
        <span className="text">{this.props.text}</span>
        <a
          className="github"
          aria-label="GitHub"
          href="https://github.com/dstanich/angular-elements-presentation"
          target="_blank"
        >
          <img src={github} />
        </a>
      </div>
    );
  }
}

export { Title };
