// angular-groceries/src/app/grocery-list/grocery-list.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

import { Item } from '../data.service';

@Component({
  selector: 'app-grocery-list',
  templateUrl: './grocery-list.component.html',
  styleUrls: ['./grocery-list.component.scss']
})
export class GroceryListComponent {
  @Input() items: Array<Item> | string;
  @Output() itemClicked: EventEmitter<string> = new EventEmitter();

  itemObjects: Array<Item>;

  constructor() {}

  ngOnInit() {
    this.itemObjects = this.parseItems(this.items);
  }

  ngOnChanges() {
    this.itemObjects = this.parseItems(this.items);
  }

  handleItemClicked(item: Item) {
    this.itemClicked.emit(item.name);
  }

  private parseItems(items: Array<Item> | string): Array<Item> {
    return Array.isArray(items) ? items : JSON.parse(items);
  }
}

<div *ngIf="itemObjects?.length > 0" class="main-container">
  <h1>Groceries</h1>
  <button
    *ngFor="let item of itemObjects; let i = index"
    class="grocery-item"
    [class.grocery-item--removed]="item.removed"
    (click)="handleItemClicked(item)"
  >
    <span class="grocery-item-count">{{ i + 1 }}.</span>
    <span>{{ item.name }}</span>
  </button>
</div>

// react-groceries/src/grocery-list/Grocery-List.tsx
import React, { Component } from 'react';
import './Grocery-List.css';
import { Item } from '../data.service';

interface Props {
  items: Array<Item>;
  itemClicked: Function;
}

interface State {
  items: Array<Item>;
}

export class GroceryList extends Component<Props, State> {
  constructor(props: any) {
    super(props);
    this.state = { items: props.items };
  }

  render() {
    return (
      <div className="GroceryList">
        {this.state.items.length > 0 ? (
          <div className="main-container">
            <h1>Groceries</h1>

            {this.state.items.map((item: Item, index: number) => {
              return (
                <button
                  key={item.name}
                  className={`grocery-item ${
                    item.removed ? 'grocery-item--removed' : ''
                  }`}
                  onClick={() => this.handleItemClicked(item)}
                >
                  <span className="grocery-item-count">{index + 1}.</span>
                  <span>{item.name}</span>
                </button>
              );
            })}
          </div>
        ) : null}
      </div>
    );
  }

  handleItemClicked = (item: Item) => {
    this.props.itemClicked(item.name);
  };
}
