// vue-groceries/src/components/Grocery-List.vue
<template>
  <div class="grocery-list">
    <div v-if="items.length > 0" class="main-container">
      <h1>Groceries</h1>
      <button
        v-for="(item, index) in items"
        :key="item.name"
        :class="['grocery-item', item.removed ? 'grocery-item--removed' : '']"
        @click="$emit('item-clicked', item.name)"
      >
        <span class="grocery-item-count">{{ index + 1 }}.</span>
        <span>{{ item.name }}</span>
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator';
import { Item } from '../data.service';

@Component
export default class GroceryList extends Vue {
  @Prop() private items!: Array<Item>;
}
</script>

<style scoped lang="scss">
.grocery-list {
  display: flex;
  justify-content: center;
  padding-bottom: 15px;
}

h1 {
  color: #07531b;
}

.main-container {
  display: flex;
  flex: 0 0 75%;
  flex-direction: column;
  align-items: center;
  background: #ffffff;
  box-shadow: 1px 1px 5px 1px #000000;
  padding: 10px 15px;

  .grocery-item {
    display: flex;
    width: 85%;
    font-size: 1.25rem;
    padding: 10px;
    margin: 5px;
    border: none;
    background: transparent;
    cursor: pointer;

    &--removed {
      opacity: 0.5;
      text-decoration: line-through;
    }

    &-count {
      width: 50px;
    }
  }
}
</style>

// react-groceries/src/grocery-list/Grocery-List.tsx
import React, { Component } from 'react';
import './Grocery-List.css';
import { Item } from '../data.service';

interface Props {
  items: Array<Item>;
  itemClicked: Function;
}

interface State {
  items: Array<Item>;
}

export class GroceryList extends Component<Props, State> {
  constructor(props: any) {
    super(props);
    this.state = { items: props.items };
  }

  render() {
    return (
      <div className="GroceryList">
        {this.state.items.length > 0 ? (
          <div className="main-container">
            <h1>Groceries</h1>

            {this.state.items.map((item: Item, index: number) => {
              return (
                <button
                  key={item.name}
                  className={`grocery-item ${
                    item.removed ? 'grocery-item--removed' : ''
                  }`}
                  onClick={() => this.handleItemClicked(item)}
                >
                  <span className="grocery-item-count">{index + 1}.</span>
                  <span>{item.name}</span>
                </button>
              );
            })}
          </div>
        ) : null}
      </div>
    );
  }

  handleItemClicked = (item: Item) => {
    this.props.itemClicked(item.name);
  };
}
